In [335]:
# importing releveant libraries
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [336]:
# reading training dataset
train_data = pd.read_csv('C:/Users/Queen.x/Downloads/train.csv')

In [337]:
train_data.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [338]:
train_data.describe()

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
count,8514.000000,8512.000000,8510.000000,8485.000000,8510.000000,8505.000000
mean,28.827930,224.687617,458.077203,173.729169,311.138778,304.854791
std,14.489021,666.717663,1611.489240,604.696458,1136.705535,1145.717189
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,19.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,38.000000,47.000000,76.000000,27.000000,59.000000,46.000000
max,79.000000,14327.000000,29813.000000,23492.000000,22408.000000,24133.000000

In [339]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8492 non-null   object
 2   CryoSleep     8476 non-null   object
 3   Cabin         8494 non-null   object
 4   Destination   8511 non-null   object
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object
 13  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB

Some labels are not in the right type. Age should be an integer and VIP should be boolean. These can only be changed after handling the NaN values

In [340]:
train_data.isnull().sum()

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

In [341]:
# NaN values in categorical columns will be replaced with mode and those in numerical columns 
# will be replaced with mean
categorical_columns = train_data.select_dtypes(['object','bool']).columns

In [342]:
categorical_columns

Index(['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'VIP',
       'Name', 'Transported'],
      dtype='object')

In [343]:
# cross-checking categorical columns
train_data.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [344]:
numerical_columns = train_data.select_dtypes(['float','int']).columns

In [345]:
numerical_columns

Index(['Age', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck'], dtype='object')

In [346]:
def ReplaceNaN(df):
    cat_col = df.select_dtypes(['object','bool'])
    num_col = df.select_dtypes(['float','int'])
    for i in cat_col:
        df[i] = df[i].fillna(df[i].mode()[0])
    for i in num_col:
        df[i] = df[i].fillna(df[i].mean())

In [347]:
ReplaceNaN(train_data)

In [348]:
train_data.isnull().sum()

PassengerId     0
HomePlanet      0
CryoSleep       0
Cabin           0
Destination     0
Age             0
VIP             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
Name            0
Transported     0
dtype: int64

In [349]:
train_data['Age'] = train_data['Age'].astype('int64')
train_data['VIP'] = train_data['VIP'].astype('bool')

In [350]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8693 non-null   object
 2   CryoSleep     8693 non-null   bool
 3   Cabin         8693 non-null   object
 4   Destination   8693 non-null   object
 5   Age           8693 non-null   int64
 6   VIP           8693 non-null   bool
 7   RoomService   8693 non-null   float64
 8   FoodCourt     8693 non-null   float64
 9   ShoppingMall  8693 non-null   float64
 10  Spa           8693 non-null   float64
 11  VRDeck        8693 non-null   float64
 12  Name          8693 non-null   object
 13  Transported   8693 non-null   bool
dtypes: bool(3), float64(5), int64(1), object(5)
memory usage: 772.6+ KB

In [351]:
# checking for duplicates in our train dataset
train_data.duplicated().value_counts()

False    8693
dtype: int64

In [352]:
train_data.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [353]:
# creating a copy of the dataset
train_data_copy = train_data.copy()

In [354]:
# removing irrelevant columns 
train_data_copy.drop(['PassengerId','Name'], axis=1, inplace=True)

In [355]:
train_data_copy.head()

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
0,Europa,False,B/0/P,TRAPPIST-1e,39,False,0.0,0.0,0.0,0.0,0.0,False
1,Earth,False,F/0/S,TRAPPIST-1e,24,False,109.0,9.0,25.0,549.0,44.0,True
2,Europa,False,A/0/S,TRAPPIST-1e,58,True,43.0,3576.0,0.0,6715.0,49.0,False
3,Europa,False,A/0/S,TRAPPIST-1e,33,False,0.0,1283.0,371.0,3329.0,193.0,False
4,Earth,False,F/1/S,TRAPPIST-1e,16,False,303.0,70.0,151.0,565.0,2.0,True

In [356]:
from sklearn.preprocessing import StandardScaler, LabelEncoder
le = LabelEncoder()
def EncodingCatColumn(df, le):
    cat_columns = df.select_dtypes(['object','bool']).columns
    le = LabelEncoder()
    for i in cat_columns:
        df[i] = le.fit_transform(df[i])

In [357]:
EncodingCatColumn(train_data_copy, le)

In [358]:
train_data_copy.head()

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
0,1,0,149,2,39,0,0.0,0.0,0.0,0.0,0.0,0
1,0,0,2184,2,24,0,109.0,9.0,25.0,549.0,44.0,1
2,1,0,1,2,58,1,43.0,3576.0,0.0,6715.0,49.0,0
3,1,0,1,2,33,0,0.0,1283.0,371.0,3329.0,193.0,0
4,0,0,2186,2,16,0,303.0,70.0,151.0,565.0,2.0,1

In [359]:
# spliting dataset into X and y values 
X = train_data_copy.drop('Transported', axis=1)
y = train_data_copy['Transported']

In [360]:
X

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
0,1,0,149,2,39,0,0.0,0.0,0.0,0.0,0.0
1,0,0,2184,2,24,0,109.0,9.0,25.0,549.0,44.0
2,1,0,1,2,58,1,43.0,3576.0,0.0,6715.0,49.0
3,1,0,1,2,33,0,0.0,1283.0,371.0,3329.0,193.0
4,0,0,2186,2,16,0,303.0,70.0,151.0,565.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...
8688,1,0,146,0,41,1,0.0,6819.0,0.0,1643.0,74.0
8689,0,1,5280,1,18,0,0.0,0.0,0.0,0.0,0.0
8690,0,0,5285,2,26,0,0.0,0.0,1872.0,1.0,0.0
8691,1,0,2131,0,32,0,0.0,1049.0,0.0,353.0,3235.0
8692,1,0,2131,2,44,0,126.0,4688.0,0.0,0.0,12.0

In [361]:
y

0       0
1       1
2       0
3       0
4       1
       ..
8688    0
8689    0
8690    1
8691    0
8692    1
Name: Transported, Length: 8693, dtype: int64

In [362]:
from sklearn.model_selection import train_test_split
from sklearn import svm

In [363]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [364]:
cls = svm.SVC(kernel='linear')

In [365]:
cls.fit(X_train, y_train)

SVC(kernel='linear')

In [366]:
pred = cls.predict(X_test)

In [367]:
pred

array([0, 1, 1, ..., 0, 1, 1], dtype=int64)

In [368]:
from sklearn.metrics import accuracy_score

In [369]:
SVM_accuracy = accuracy_score(y_test, pred)

In [370]:
from sklearn.tree import DecisionTreeClassifier

In [371]:
dcls = DecisionTreeClassifier(max_leaf_nodes= 50)

In [372]:
dcls.fit(X_train, y_train)

DecisionTreeClassifier(max_leaf_nodes=50)

In [373]:
dpred = dcls.predict(X_test)

In [374]:
DC_accuracy = accuracy_score(y_test, dpred)

In [375]:
print(f"Accuracy of DecisionTreeClassifier is {DC_accuracy}")
print(f"Accuracy of SupportVectorMachine is {SVM_accuracy}")

Accuracy of DecisionTreeClassifier is 0.7833588957055214
Accuracy of SupportVectorMachine is 0.772239263803681

In [376]:
# importing test dataset
test = pd.read_csv('C:/Users/Queen.x/Downloads/test.csv')

In [377]:
test.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,0013_01,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,Nelly Carsoning
1,0018_01,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,Lerome Peckers
2,0019_01,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,Sabih Unhearfus
3,0021_01,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,Meratz Caltilter
4,0023_01,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,Brence Harperez

In [378]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4277 entries, 0 to 4276
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   4277 non-null   object
 1   HomePlanet    4190 non-null   object
 2   CryoSleep     4184 non-null   object
 3   Cabin         4177 non-null   object
 4   Destination   4185 non-null   object
 5   Age           4186 non-null   float64
 6   VIP           4184 non-null   object
 7   RoomService   4195 non-null   float64
 8   FoodCourt     4171 non-null   float64
 9   ShoppingMall  4179 non-null   float64
 10  Spa           4176 non-null   float64
 11  VRDeck        4197 non-null   float64
 12  Name          4183 non-null   object
dtypes: float64(6), object(7)
memory usage: 434.5+ KB

In [379]:
test.isnull().sum()

PassengerId       0
HomePlanet       87
CryoSleep        93
Cabin           100
Destination      92
Age              91
VIP              93
RoomService      82
FoodCourt       106
ShoppingMall     98
Spa             101
VRDeck           80
Name             94
dtype: int64

In [380]:
# replacing null values with ReplaceNaN function 
ReplaceNaN(test)

In [381]:
test.isnull().sum()

PassengerId     0
HomePlanet      0
CryoSleep       0
Cabin           0
Destination     0
Age             0
VIP             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
Name            0
dtype: int64

In [382]:
# convering Age and VIP to the appropriate datatypes
test['Age'] = test['Age'].astype('int64')
test['VIP'] = test['VIP'].astype('bool')

In [383]:
# making a copy of test dataset
test_copy = test.copy()

In [384]:
len(test_copy)

4277

In [385]:
# checking for duplicates
test_copy.duplicated().value_counts()

False    4277
dtype: int64

In [386]:
# dropping irrelevant columns 
test_copy.drop(['PassengerId', 'Name'], axis=1, inplace=True)

In [387]:
len(test_copy)

4277

In [389]:
# Encode categorical columns with the EncodingCatColumn function 
EncodingCatColumn(test_copy, le)

In [390]:
test_copy.head()

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
0,0,1,2784,2,27,0,0.0,0.0,0.0,0.0,0.0
1,0,0,1867,2,19,0,0.0,9.0,0.0,2823.0,0.0
2,1,1,257,0,31,0,0.0,0.0,0.0,0.0,0.0
3,1,0,259,2,38,0,0.0,6652.0,0.0,181.0,585.0
4,0,0,1940,2,20,0,10.0,0.0,635.0,0.0,0.0

In [391]:
output = dcls.predict(test_copy)

In [392]:
output = list(output)

In [393]:
new_otput = []
for i in output:
    if i == 1:
        a="True"
        new_otput.append(a)
    else:
        a = "False"
        new_otput.append(a)

In [ ]:
new_otput

['True',
 'False',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'False',
 'False',
 'True',
 'True',
 'False',
 'False',
 'False',
 'True',
 'True',
 'False',
 'False',
 'False',
 'True',
 'True',
 'False',
 'False',
 'True',
 'True',
 'True',
 'True',
 'True',
 'False',
 'True',
 'False',
 'False',
 'False',
 'True',
 'True',
 'True',
 'False',
 'True',
 'False',
 'True',
 'False',
 'False',
 'True',
 'False',
 'False',
 'False',
 'False',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'False',
 'True',
 'True',
 'False',
 'True',
 'False',
 'False',
 'True',
 'True',
 'False',
 'True',
 'False',
 'False',
 'False',
 'False',
 'True',
 'False',
 'False',
 'True',
 'False',
 'True',
 'True',
 'False',
 'True',
 'True',
 'False',
 'False',
 'False',
 'True',
 'True',
 'True',
 'False',
 'True',
 'True',
 'False',
 'False',
 'False',
 'False',
 'False',
 'False',
 'True',
 'False',
 'True',
 'False',
 'True',
 'True',
 'True',
 'False',
 'True',
 'False',
 'True',
 'True',
 'False',
 'True',
 'True',
 'False',
 'True',
 'True',
 'False',
 'True',
 'True',
 'False',
 'False',
 'False',
 'False',
 'False',
 'False',
 'False',
 'True',
 'True',
 'False',
 'False',
 'True',
 'False',
 'True',
 'False',
 'True',
 'True',
 'False',
 'True',
 'True',
 'False',
 'False',
 'False',
 'True',
 'True',
 'True',
 'False',
 'True',
 'False',
 'True',
 'True',
 'False',
 'True',
 'True',
 'True',
 'True',
 'False',
 'False',
 'True',
 'True',
 'True',
 'False',
 'False',
 'False',
 'False',
 'True',
 'True',
 'False',
 'False',
 'True',
 'False',
 'True',
 'False',
 'False',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'False',
 'True',
 'False',
 'False',
 'True',
 'False',
 'False',
 'False',
 'False',
 'True',
 'False',
 'True',
 'True',
 'True',
 'True',
 'False',
 'False',
 'False',
 'False',
 'False',
 'True',
 'True',
 'False',
 'True',
 'False',
 'False',
 'False',
 'True',
 'True',
 'False',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'False',
 'True',
 'False',
 'True',
 'True',
 'True',
 'True',
 'True',
 'False',
 'True',
 'True',
 'True',
 'False',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'False',
 'False',
 'False',
 'False',
 'True',
 'True',
 'False',
 'True',
 'True',
 'False',
 'True',
 'True',
 'True',
 'False',
 'False',
 'True',
 'False',
 'True',
 'False',
 'True',
 'False',
 'True',
 'True',
 'True',
 'False',
 'True',
 'True',
 'True',
 'True',
 'True',
 'False',
 'True',
 'False',
 'True',
 'False',
 'True',
 'True',
 'False',
 'True',
 'False',
 'True',
 'True',
 'True',
 'False',
 'False',
 'False',
 'True',
 'True',
 'False',
 'False',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'False',
 'False',
 'True',
 'True',
 'True',
 'False',
 'False',
 'False',
 'True',
 'True',
 'False',
 'False',
 'False',
 'False',
 'True',
 'True',
 'True',
 'True',
 'False',
 'False',
 'False',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'False',
 'False',
 'True',
 'True',
 'True',
 'False',
 'False',
 'True',
 'True',
 'True',
 'True',
 'False',
 'False',
 'True',
 'True',
 'True',
 'False',
 'True',
 'False',
 'False',
 'True',
 'False',
 'False',
 'False',
 'False',
 'False',
 'False',
 'True',
 'True',
 'True',
 'False',
 'False',
 'True',
 'False',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'False',
 'True',
 'False',
 'True',
 'False',
 'True',
 'False',
 'True',
 'True',
 'False',
 'True',
 'True',
 'True',
 'True',
 'False',
 'True',
 'True',
 'True',
 'True',
 'True',
 'False',
 'True',
 'False',
 'True',
 'True',
 'True',
 'True',
 'False',
 'True',
 'False',
 'False',
 'True',
 'True',
 'True',
 'False',
 'True',
 'True',
 'False',
 'True',
 'False',
 'False',
 'True',
 'True',
 'True',
 'False',
 'True',
 'True',
 'True',
 'False',
 'True',
 'False',
 'True',
 'False',
 'True',
 'False',
 'True',
 'True',
 'True',
 'False',
 'True',
 'True',
 'False',
 'False',
 'False',
 'False',
 'True',
 'True',
 'False',
 'False',
 'False',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'False',
 'False',
 'True',
 'True',
 'True',
 'True',
 'False',
 'True',
 'True',
 'False',
 'False',
 'True',
 'False',
 'False',
 'False',
 'False',
 'True',
 'True',
 'True',
 'False',
 'False',
 'False',
 'False',
 'True',
 'True',
 'False',
 'False',
 'True',
 'True',
 'False',
 'False',
 'False',
 'True',
 'False',
 'False',
 'True',
 'False',
 'True',
 'False',
 'True',
 'False',
 'False',
 'False',
 'False',
 'True',
 'False',
 'False',
 'True',
 'True',
 'True',
 'False',
 'False',
 'True',
 'True',
 'False',
 'True',
 'True',
 'True',
 'True',
 'False',
 'False',
 'True',
 'True',
 'True',
 'True',
 'False',
 'False',
 'False',
 'False',
 'True',
 'True',
 'False',
 'True',
 'True',
 'False',
 'False',
 'True',
 'False',
 'True',
 'False',
 'False',
 'False',
 'True',
 'False',
 'True',
 'False',
 'False',
 'True',
 'True',
 'False',
 'False',
 'True',
 'True',
 'False',
 'False',
 'False',
 'True',
 'True',
 'True',
 'True',
 'True',
 'False',
 'False',
 'True',
 'True',
 'True',
 'True',
 'True',
 'False',
 'True',
 'False',
 'True',
 'True',
 'False',
 'True',
 'True',
 'True',
 'True',
 'True',
 'False',
 'True',
 'False',
 'False',
 'True',
 'True',
 'True',
 'False',
 'True',
 'False',
 'True',
 'False',
 'True',
 'False',
 'False',
 'True',
 'False',
 'True',
 'True',
 'False',
 'False',
 'False',
 'False',
 'False',
 'True',
 'False',
 'True',
 'False',
 'True',
 'False',
 'False',
 'False',
 'True',
 'True',
 'False',
 'False',
 'True',
 'True',
 'False',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'False',
 'True',
 'True',
 'True',
 'False',
 'True',
 'False',
 'False',
 'True',
 'True',
 'False',
 'True',
 'False',
 'False',
 'True',
 'False',
 'True',
 'True',
 'False',
 'False',
 'True',
 'False',
 'False',
 'False',
 'True',
 'False',
 'False',
 'True',
 'True',
 'True',
 'True',
 'True',
 'False',
 'False',
 'True',
 'False',
 'False',
 'True',
 'True',
 'True',
 'True',
 'False',
 'False',
 'True',
 'False',
 'False',
 'True',
 'True',
 'True',
 'False',
 'True',
 'False',
 'False',
 'True',
 'False',
 'False',
 'False',
 'True',
 'True',
 'False',
 'True',
 'True',
 'True',
 'True',
 'True',
 'False',
 'True',
 'False',
 'False',
 'True',
 'False',
 'False',
 'False',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'False',
 'True',
 'True',
 'True',
 'True',
 'False',
 'False',
 'False',
 'False',
 'False',
 'True',
 'False',
 'False',
 'False',
 'False',
 'False',
 'False',
 'False',
 'False',
 'True',
 'False',
 'False',
 'False',
 'True',
 'False',
 'True',
 'False',
 'False',
 'True',
 'True',
 'False',
 'False',
 'True',
 'False',
 'True',
 'False',
 'True',
 'True',
 'True',
 'True',
 'True',
 'False',
 'False',
 'False',
 'False',
 'False',
 'True',
 'True',
 'True',
 'True',
 'False',
 'True',
 'True',
 'True',
 'False',
 'False',
 'False',
 'False',
 'True',
 'True',
 'False',
 'False',
 'False',
 'False',
 'False',
 'True',
 'True',
 'False',
 'False',
 'False',
 'True',
 'False',
 'False',
 'True',
 'True',
 'True',
 'False',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'False',
 'False',
 'True',
 'True',
 'True',
 'False',
 'True',
 'False',
 'True',
 'True',
 'False',
 'False',
 'True',
 'False',
 'True',
 'False',
 'False',
 'True',
 'False',
 'True',
 'True',
 'False',
 'False',
 'False',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'False',
 'True',
 'False',
 'False',
 'True',
 'True',
 'False',
 'True',
 'True',
 'True',
 'False',
 'True',
 'False',
 'True',
 'False',
 'True',
 'False',
 'False',
 'False',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'False',
 'False',
 'False',
 'False',
 'False',
 'False',
 'True',
 'False',
 'True',
 'False',
 'False',
 'False',
 'True',
 'False',
 'False',
 'False',
 'True',
 'True',
 'True',
 'True',
 'False',
 'True',
 'True',
 'False',
 'False',
 'True',
 'False',
 'False',
 'False',
 'False',
 'False',
 'True',
 'True',
 'True',
 'True',
 'False',
 'True',
 'False',
 'False',
 'True',
 'False',
 'True',
 'False',
 'True',
 'False',
 'True',
 'False',
 'True',
 'False',
 'True',
 'True',
 'True',
 'False',
 'True',
 'True',
 'True',
 'True',
 'False',
 'True',
 'False',
 'False',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'False',
 'False',
 'False',
 'True',
 'False',
 'False',
 'True',
 'False',
 'True',
 'False',
 'True',
 'True',
 'False',
 'False',
 'True',
 'False',
 'True',
 'True',
 'False',
 'True',
 'False',
 'False',
 'True',
 'False',
 'True',
 'True',
 'True',
 'True',
 'True',
 'False',
 'False',
 'False',
 'True',
 'False',
 'False',
 'False',
 'False',
 'False',
 'False',
 'False',
 'False',
 'True',
 'False',
 'True',
 'False',
 'False',
 'False',
 'False',
 'True',
 'True',
 'False',
 'True',
 'False',
 'True',
 'False',
 'True',
 'True',
 'True',
 'False',
 'True',
 'True',
 'False',
 'False',
 'False',
 'True',
 'True',
 'False',
 'True',
 'False',
 'True',
 'True',
 'True',
 'False',
 'True',
 'True',
 'False',
 'True',
 'False',
 'False',
 'False',
 'True',
 'True',
 'False',
 'False',
 'True',
 'False',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'False',
 'True',
 'False',
 'False',
 'True',
 'True',
 'False',
 'True',
 'True',
 'True',
 'True',
 ...]

In [394]:
output = np.array(new_otput)

In [395]:
output

array(['True', 'False', 'True', ..., 'True', 'True', 'True'], dtype='<U5')

In [398]:
test['Transported'] = output.tolist()

In [401]:
test.columns

Index(['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age',
       'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck',
       'Name', 'Transported'],
      dtype='object')

In [402]:
test.drop(['HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age',
       'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck',
       'Name'], axis=1, inplace=True)

In [407]:
test.head()

  PassengerId Transported
0     0013_01        True
1     0018_01       False
2     0019_01        True
3     0021_01        True
4     0023_01        True

In [408]:
test.tail()

     PassengerId Transported
4272     9266_02        True
4273     9269_01       False
4274     9271_01        True
4275     9273_01        True
4276     9277_01        True

In [410]:
test.to_csv("Submission.csv", index=False)